### ISSUE TITLE
getOffers does not increment impressions

### ISSUE THREAD

**Issue by evidana** [adobe/target-java-sdk#20]
### Expected Behaviour
Impressions to increment in the Target interface.

### Actual Behaviour
Impressions remain at 0 for Production and Development environments.

### Reproduce Scenario (including but not limited to)
Issue a getOffers request

#### Platform and Version
1.1

#### Sample Code that illustrates the problem
Can provide in a more secure format.

#### Logs taken while reproducing problem
Can provide in a more secure format.

**Comment by sheshanathkumar** [comment]
Hi, can I work on this issue ?

**Comment by jasonwaters** [comment]
This issue needs more detail to be actionable.  Please provide a sample code that illustrates the problem.

Also, you may not be aware of it, but if you make a `prefetch` request, you will need to manually send a notification using the `sendNotifications` method in order for impressions to be captured and appear in reports.  But if you make an `execute` request, the notification is handled for you and you.  

Please re-open this issue providing a sample code if you continue to have the problem.

**Comment by evidana** [comment]
Understood. The issue was that Target was treating my request as a bot due to user agent string.
