### ISSUE TITLE
Running the SDK behind a proxy times out and throws a NullPointerException

### ISSUE THREAD

**Issue by hisham-hassan** [adobe/target-java-sdk#5]
### Expected Behaviour
We need to be able to use the SDK on a server that is running behind a proxy.
We could not find any documentation that specifies how a proxy could be configured for the Target HTTP client.

### Actual Behaviour
Running the SDK behind a proxy times out and throws a NullPointerException. Running the same code on a server with direct internet connection works well.

#### Steps to Reproduce
Run the SDK on any PC that is behind a corporate firewall and that requires a proxy configuration to allow external internet calls.

#### Platform and Version
Java 1.8
Adobe Target SDK 1.0.1

#### Sample Code that illustrates the problem
Running this line behind in a network that requires a proxy would timeout and throw a null pointer exception.
```
TargetDeliveryResponse targetDeliveryResponse = targetClient.getOffers(targetDeliveryRequest);
```

#### Logs taken while reproducing problem
```
Exception in thread "main" com.adobe.target.edge.client.service.TargetRequestException
	at com.adobe.target.edge.client.DefaultTargetClient.getOffers(DefaultTargetClient.java:46)
	at TargetSDKTest.main(TargetSDKTest.java:48)
Caused by: java.lang.NullPointerException
	at com.adobe.target.edge.client.http.TargetMetrics.lambda$begin$0(TargetMetrics.java:36)
	at kong.unirest.apache.ApacheClient.request(ApacheClient.java:132)
	at kong.unirest.BaseRequest.asObject(BaseRequest.java:230)
	at com.adobe.target.edge.client.http.DefaultTargetHttpClient.execute(DefaultTargetHttpClient.java:69)
	at com.adobe.target.edge.client.http.TargetHttpClientLoggingDecorator.execute(TargetHttpClientLoggingDecorator.java:34)
	at com.adobe.target.edge.client.service.DefaultTargetService.executeRequest(DefaultTargetService.java:59)
	at com.adobe.target.edge.client.DefaultTargetClient.getOffers(DefaultTargetClient.java:43)
	... 1 more
```

### Possible Fix
The code can be enhanced to enable the customers to set their proxy when needed. this could be achieved by making the following changes:

1- Create a new ClientProxyConfig class to hold the proxy details.
```
package com.adobe.target.edge.client;

public class ClientProxyConfig {
	private String address;
	private String port;
	private String userName;
	private String password;
	private boolean authProxy = false; 
	
	public ClientProxyConfig(String proxyAddress, String proxyPort) {
		this.address = proxyAddress;
		this.port = proxyPort;
	}
	
	public ClientProxyConfig(String address, String port, String userName, String password) {
		this.address = address;
		this.port = port;
		this.userName = userName;
		this.password = password;
		authProxy = true;
	}

	public String getAddress() {
		return address;
	}

	public String getPort() {
		return port;
	}

	public String getUserName() {
		return userName;
	}

	public String getPassword() {
		return password;
	}

	public boolean isAuthProxy() {
		return authProxy;
	}
}
```

2- Update the com.adobe.target.edge.client.ClientConfig class to have an instance of the ClientProxyConfig
```
private ClientProxyConfig proxy;

public ClientProxyConfig getProxy() {
	return proxy;
}

public void setProxy(ClientProxyConfig proxy) {
	this.proxy = proxy;
}

public boolean isProxyEnabled() {
	return proxy != null;
}
```

3- Update the constructor of the com.adobe.target.edge.client.http.DefaultTargetHttpClient class to have the following lines:
```
if (clientConfig.isProxyEnabled()) {
    ClientProxyConfig proxy = clientConfig.getProxy();
    if(proxy.isAuthProxy()) {
        unirestInstance.config().proxy(proxy.getAddress(), proxy.getPort, proxy.getUserName(), proxy.getPassword);
    } else {
        unirestInstance.config().proxy(proxy.getAddress(), proxy.getPort);
    }
}
```

**Comment by XDex** [comment]
@hisham-hassan Considering that you've already provided most of the fix here, could you please raise a PR with the fix?

**Comment by hisham-hassan** [comment]
Great Idea @XDex; will do that. Cheers!

**Comment by hisham-hassan** [comment]
Hi @XDex , any chance we could get minor release with the merged proxy pull request (https://github.com/adobe/target-java-sdk/pull/6) ? Our team is keen to use the SDK but all our servers are behind a proxy.

**Comment by artur-ciocanu** [comment]
@hisham-hassan `v1.1.0` has been released. Thanks a lot for your contribution.

**Comment by dogrizz** [comment]
Hey, fix is incomplete.
There is still an NPE thrown if you forget to use a proxy (or if your company switches certs and there is a SSLHandshake error ;) ).
`TargetMetrics#begin` is not handling `exception` parameter in anyway resulting in access to `responseSummary` which is `null`.

But either way, there is no meaningful message.

**Comment by artur-ciocanu** [comment]
> Hey, fix is incomplete.
> There is still an NPE thrown if you forget to use a proxy (or if your company switches certs and there is a SSLHandshake error ;) ).
> `TargetMetrics#begin` is not handling `exception` parameter in anyway resulting in access to `responseSummary` which is `null`.
> 
> But either way, there is no meaningful message.

@dogrizz could you please create an issue with the right steps to reproduce the NPE. Thanks a lot for your help!

**Comment by artur-ciocanu** [comment]
> Hey, fix is incomplete.
> There is still an NPE thrown if you forget to use a proxy (or if your company switches certs and there is a SSLHandshake error ;) ).
> `TargetMetrics#begin` is not handling `exception` parameter in anyway resulting in access to `responseSummary` which is `null`.
> 
> But either way, there is no meaningful message.

@dogrizz thanks for your input, we will take a look and get back to you.
